import { grade, statusTone, type AnalysisResult } from "./analyzer";

const QUOTE_LABEL = { found: "You wrote", anchor: "Nearest text in your PRD", vague: "Vague wording", empty: "Placeholder section" } as const;

export function reportMarkdown(r: AnalysisResult): string {
  const g = grade(r.overall);
  const by = (id: string) => r.categories.find((c) => c.id === id)!;
  const delta = r.prev ? ` (${r.overall - r.prev.overall >= 0 ? "+" : ""}${r.overall - r.prev.overall} since last time)` : "";
  const L: string[] = [
    `# PRD Doctor report: ${r.title}`,
    "",
    `**Score: ${r.overall}/100** · ${g.label}${delta} · ${r.words} words · ${new Date(r.createdAt).toLocaleDateString()}`,
    "",
    "## Category scores",
    "",
    "| Category | Score | Status |",
    "|---|---:|---|",
    ...r.categories.map((c) => `| ${c.label} | ${c.score} | ${statusTone(c.status).label} |`),
    "",
    "## Where to start",
    "",
    ...r.weakest.map((id, i) => `${i + 1}. **${by(id).label}** (${by(id).score}/100): ${by(id).missing[0] ?? by(id).why}`),
    "",
    "## Fixes",
    "",
  ];
  r.categories.filter((c) => c.status !== "strong").sort((a, b) => a.score - b.score).forEach((c) => {
    L.push(`### ${c.label} (${c.score}/100)`, "");
    L.push(c.quote ? `> ${QUOTE_LABEL[c.quote.kind]}: “${c.quote.text}”` : "> No mention found in your PRD.", "");
    L.push(`- **Missing:** ${c.missing.join("; ") || "signals found are thin"}`);
    L.push(`- **Why it matters:** ${c.why}`);
    L.push(`- **What to add:** ${c.add}`);
    L.push(`- **Question:** ${c.question}`, "");
  });
  L.push("## Suggested rewrite", "", r.rewrite, "", "---", "Generated by PRD Doctor · https://prd-doctor.vercel.app");
  return L.join("\n");
}

export function fixMarkdown(c: AnalysisResult["categories"][number]): string {
  return [
    `${c.label} (${c.score}/100)`,
    c.quote ? `${QUOTE_LABEL[c.quote.kind]}: “${c.quote.text}”` : "No mention found in your PRD.",
    `Missing: ${c.missing.join("; ") || "signals found are thin"}`,
    `Add: ${c.add}`,
    `Question: ${c.question}`,
  ].join("\n");
}

export function downloadText(filename: string, text: string, type = "text/markdown") {
  const a = document.createElement("a");
  a.href = URL.createObjectURL(new Blob([text], { type: `${type};charset=utf-8` }));
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}
